import { Component, OnDestroy, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { UploadService } from './upload.service';

@Component({selector:'app-upload-page',imports:[RouterLink],template:`
<section class="page upload-page"><a class="back" routerLink="/projects">← Projects</a><div class="heading"><div><p class="eyebrow">BƯỚC 1 / 3</p><h1>Upload video nguồn</h1><p>Video được gửi thẳng tới object storage bằng URL tạm thời.</p></div><span class="security">◆ Mã hóa khi truyền</span></div>
<div class="layout"><div class="drop card" [class.dragging]="dragging()" (dragover)="drag($event,true)" (dragleave)="drag($event,false)" (drop)="drop($event)"><input #picker type="file" accept="video/mp4,video/quicktime,video/webm,video/x-matroska" (change)="pick($event)" hidden /><div class="upload-icon">↑</div><h2>{{file()?.name||'Thả video vào đây'}}</h2>@if(file()){<p>{{formatSize(file()!.size)}} · {{file()!.type}}</p>}@else{<p>MP4, MOV, MKV hoặc WebM · tối đa 5 GB</p>}<button class="btn btn-secondary" type="button" (click)="picker.click()">{{file()?'Chọn file khác':'Chọn từ máy'}}</button></div>
<aside class="card"><p class="eyebrow">TRƯỚC KHI UPLOAD</p><h3>Checklist chất lượng</h3><ul><li><span>✓</span> Âm thanh lời nói rõ ràng</li><li><span>✓</span> Video không bị hỏng</li><li><span>✓</span> Bạn có quyền sử dụng nội dung</li></ul><div class="tip"><strong>Mẹo</strong><p>Audio sạch giúp transcript và lồng tiếng khớp tốt hơn.</p></div></aside></div>
@if(error()){<p class="error" role="alert">{{error()}}</p>}@if(uploading()){<div class="progress card"><div><strong>Đang upload…</strong><span>{{progress()}}%</span></div><div class="track"><i [style.width.%]="progress()"></i></div><button type="button" (click)="cancel()">Hủy</button></div>}
<div class="footer"><span>File không đi qua server API</span><button class="btn btn-primary" [disabled]="!file()||uploading()" (click)="start()">{{uploading()?'Đang upload…':'Upload và tiếp tục →'}}</button></div>
</section>`,styles:[`
.back{display:inline-block;color:var(--muted);text-decoration:none;margin-bottom:2rem}.heading{display:flex;justify-content:space-between;align-items:end;margin-bottom:2rem}.heading h1{font-size:clamp(2.2rem,5vw,4.2rem);margin:.35rem 0}.heading p{color:var(--muted)}.security{font-size:.8rem;color:var(--accent);font-weight:700}.layout{display:grid;grid-template-columns:2fr 1fr;gap:1.2rem}.drop{min-height:370px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;border:1.5px dashed #c8c8dd;box-shadow:none;transition:.2s}.drop.dragging{border-color:var(--brand);background:var(--brand-soft)}.upload-icon{display:grid;place-items:center;width:66px;height:66px;border-radius:22px;background:var(--brand-soft);color:var(--brand);font-size:2rem}.drop h2{margin:1rem 0 .35rem}.drop p{color:var(--muted);margin:0 0 1.2rem}aside{padding:1.6rem;box-shadow:none}aside h3{font-size:1.35rem}ul{list-style:none;padding:0;display:grid;gap:1rem;color:#50586b}li span{display:inline-grid;place-items:center;width:22px;height:22px;margin-right:.55rem;border-radius:50%;background:#e6f8f2;color:var(--accent);font-weight:800}.tip{margin-top:2rem;padding:1rem;border-radius:13px;background:#f1f2f7}.tip p{color:var(--muted);font-size:.87rem;margin:.35rem 0}.footer{display:flex;justify-content:space-between;align-items:center;margin-top:1.3rem}.footer span{color:var(--muted);font-size:.82rem}.progress{margin-top:1rem;padding:1rem 1.2rem;box-shadow:none}.progress>div:first-child{display:flex;justify-content:space-between}.track{height:8px;background:#ececf3;border-radius:10px;margin:.7rem 0;overflow:hidden}.track i{display:block;height:100%;background:var(--brand)}.progress button{border:0;background:none;color:var(--danger);cursor:pointer;padding:0}@media(max-width:800px){.heading{align-items:start;flex-direction:column}.security{margin-top:1rem}.layout{grid-template-columns:1fr}.footer{align-items:stretch;flex-direction:column;gap:1rem}.footer .btn{width:100%}}
`]})
export class UploadPage implements OnDestroy{private readonly route=inject(ActivatedRoute);readonly projectId=this.route.snapshot.paramMap.get('projectId')!;readonly file=signal<File|null>(null);readonly dragging=signal(false);readonly uploading=signal(false);readonly progress=signal(0);readonly error=signal('');constructor(private uploader:UploadService){}pick(event:Event):void{const input=event.target as HTMLInputElement;this.select(input.files?.[0])}drag(event:DragEvent,on:boolean):void{event.preventDefault();this.dragging.set(on)}drop(event:DragEvent):void{event.preventDefault();this.dragging.set(false);this.select(event.dataTransfer?.files[0])}select(file?:File):void{this.error.set('');if(!file)return;if(file.size>5*1024**3){this.error.set('Video vượt quá giới hạn 5 GB.');return}if(file.type&&!file.type.startsWith('video/')){this.error.set('Vui lòng chọn một file video.');return}this.file.set(file)}async start():Promise<void>{const file=this.file();if(!file)return;this.uploading.set(true);this.error.set('');try{await this.uploader.upload(this.projectId,file,v=>this.progress.set(v));this.progress.set(100)}catch(e){if((e as Error).name!=='AbortError')this.error.set((e as Error).message||'Upload không thành công.')}finally{this.uploading.set(false)}}cancel():void{this.uploader.cancel();this.uploading.set(false)}formatSize(bytes:number):string{return bytes>=1024**3?`${(bytes/1024**3).toFixed(2)} GB`:`${(bytes/1024**2).toFixed(1)} MB`}ngOnDestroy():void{if(this.uploading())this.uploader.cancel()}}
