import { Component, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { apiErrorMessage } from '../../core/api/api-error';
import { ProjectService } from './project.service';

@Component({selector:'app-project-create',imports:[ReactiveFormsModule,RouterLink],template:`
<section class="page narrow"><a class="back" routerLink="/projects">← Quay lại projects</a><p class="eyebrow">PROJECT MỚI</p><h1>Video này sẽ nói ngôn ngữ nào?</h1><p class="intro">Thiết lập cơ bản trước khi upload. Bạn có thể đổi voice và subtitle sau.</p>
<form class="card" [formGroup]="form" (ngSubmit)="submit()"><div class="field full"><label for="name">Tên project</label><input id="name" formControlName="name" placeholder="Ví dụ: Product launch — Vietnamese" /></div><div class="field"><label for="source">Ngôn ngữ gốc</label><select id="source" formControlName="sourceLanguage"><option value="en">English</option><option value="vi">Tiếng Việt</option><option value="ja">日本語</option><option value="ko">한국어</option><option value="zh">中文</option></select></div><div class="swap">→</div><div class="field"><label for="target">Dịch sang</label><select id="target" formControlName="targetLanguage"><option value="vi">Tiếng Việt</option><option value="en">English</option><option value="ja">日本語</option><option value="ko">한국어</option><option value="zh">中文</option></select></div><label class="check full"><input type="checkbox" formControlName="subtitleEnabled" /><span><strong>Tạo phụ đề</strong><small>Sinh file SRT/VTT và cho phép burn-in khi render.</small></span></label>@if(error()){<p class="error full">{{error()}}</p>}<div class="actions full"><a class="btn btn-secondary" routerLink="/projects">Hủy</a><button class="btn btn-primary" [disabled]="form.invalid||submitting()">{{submitting()?'Đang tạo…':'Tiếp tục upload →'}}</button></div></form></section>`,styles:[`
.narrow{max-width:780px}.back{display:inline-block;color:var(--muted);text-decoration:none;margin-bottom:3rem}.narrow h1{font-size:clamp(2.2rem,5vw,4.4rem);line-height:1.05;margin:.5rem 0}.intro{color:var(--muted);font-size:1.05rem;margin-bottom:2rem}.card{display:grid;grid-template-columns:1fr auto 1fr;gap:1.25rem;align-items:end;padding:2rem}.full{grid-column:1/-1}.swap{padding-bottom:.9rem;color:var(--brand);font-weight:800}.check{display:flex;gap:.8rem;padding:1rem;border-radius:12px;background:var(--brand-soft)}.check input{accent-color:var(--brand);width:18px}.check span{display:grid;gap:.2rem}.check small{color:var(--muted)}.actions{display:flex;justify-content:flex-end;gap:.7rem;margin-top:.5rem}@media(max-width:650px){.card{grid-template-columns:1fr}.full{grid-column:1}.swap{display:none}}
`]})
export class ProjectCreatePage{readonly submitting=signal(false);readonly error=signal('');readonly form=new FormGroup({name:new FormControl('',[Validators.required,Validators.maxLength(180)]),sourceLanguage:new FormControl('en',{nonNullable:true}),targetLanguage:new FormControl('vi',{nonNullable:true}),subtitleEnabled:new FormControl(true,{nonNullable:true})});constructor(private service:ProjectService,private router:Router){}submit():void{if(this.form.invalid)return;this.submitting.set(true);this.service.create(this.form.getRawValue() as any).pipe(finalize(()=>this.submitting.set(false))).subscribe({next:p=>void this.router.navigate(['/projects',p.id,'upload']),error:e=>this.error.set(apiErrorMessage(e))})}}
